theme: jekyll-theme-minimal
title: fastqc-rs
description: A quality control tool for FASTQ files written in rust.
logo: https://raw.githubusercontent.com/fxwiegand/fastqc-rs/gh-pages/img/fastqc-rs-ferris.png
